name: ev_instagram
favicon: null
layout_spectrum: 0.01779016014188528
typography_spectrum: 0.5380874974653125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000100'
    - '#feffff'
    - '#00ff0d'
    - '#019cf9'
    - '#9d1203'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
